services:
  backend:
    build: ./backend
    container_name: campus-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: campus-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend